all: spectre_tester_guest spectre_scanner_host

spectre_tester_guest: spectre_tester_guest.o
spectre_scanner_host: spectre_scanner_host.o

clean:
	rm -rf spectre_tester_guest spectre_scanner_host *.o
